### ISSUE TITLE
app items should open in a new link

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-explore#10]
Apps that are included in collections should open in a new link when clicked.

**Comment by pyphilia** [comment]
- Activities (these should open the activity in “demo” mode).
  - Apps (these should just open the link in a new window).
  - Links (open in new window)
  - PDFs, Images, Videos (for now we can just open in new tab, but eventually we can have a viewer).
  - Other spaces (if they are public, they open as another collection).
