### ISSUE TITLE
Run within a Docker environment so that it can be deployed to AWS Fargate

### ISSUE THREAD

**Issue by hasanagh** [graasp/graasp-explore#14]

**Comment by hasanagh** [comment]
I found this docker file we can use

`
FROM node:alpine

ENV NODE_ENV production
ENV HOST 0.0.0.0
ENV PORT 80

ENV RAZZLE_CUSTOM_VARIABLE x

# Bundle APP files
COPY build .
COPY package.json .
COPY package-lock.json .
COPY build/public public

RUN npm install --production

CMD [ "node", "build/server.js" ]`

**Comment by pyphilia** [comment]
closed with #20 and fix in #24
