### ISSUE TITLE
improve homepage design

### ISSUE THREAD

**Issue by juancarlosfarah** [graasp/graasp-explore#27]
Homepage design should look something like the home pages of data repositories or search engines.

Example:

openneuro.org

Basic Scaffolding only (i.e. no big design needed).

- Banner with title and main message.
- Search bar
- Featured collections (which are selected and flagged in the backend somehow).
- Make search results span the whole page in a modal that is "closable".

**Comment by pyphilia** [comment]
https://openneuro.org/
