### ISSUE TITLE
Add a logger

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-explore#34]
Add an issue to add a logger like the one we have for the API. Then we won't get any of these errors.

_Originally posted by @juancarlosfarah in https://github.com/graasp/graasp-explore/pull/24#discussion_r567025736_

**Comment by juancarlosfarah** [comment]
@pyphilia, this is the logger ticket.

**Comment by juancarlosfarah** [comment]
You can copy the logger from here:

https://github.com/react-epfl/graasp-api/blob/master/src/utils/logger.js
